CREATE TABLE assessments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER DEFAULT 0 NOT NULL,
  tool VARCHAR2(50) NOT NULL,
  external_id VARCHAR2(100) NOT NULL,
  score NUMBER(6,3),
  label VARCHAR2(50),
  ts TIMESTAMP NOT NULL,
  data_source VARCHAR2(50) NOT NULL,
  version VARCHAR2(20) NOT NULL,
  ingested_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_tool_external ON assessments(tool, external_id);
CREATE INDEX ix_user_ts ON assessments(user_id, ts);
